<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Welcome to You Suck App</title>
		<meta charset="utf-8" />
		<meta name="keywords" content="You suck, complaints, gripes, customer service, bad experience" />
		<meta name="description" content="We group your complaints so you can be heard" />
		<link rel="stylesheet" href="css/ys.css" />
		<style>
		</style>
		<script src="js/ys.js"></script>
	</head>
	<body>
		<div id="welcome">
   			 <h1>Welcome to the YouSuck App</h1>
   			 <h2>This is your project's main page</h2>
    		</div>
	</body>

    <?php $user = $this->html;
        echo $user->getId();
        echo $user->getName();
?>
</html>
