<div class="grid_12 upper">
	<hgroup class="complaints">
   		<h1>Making Complaints Useful</h1>
   		<h2><span>Don't let your voice go unheard. Tell others and </span>spread the word to change stuff for the better.</h2>
  	</hgroup>
	<div class="suffer feature">
   		<img src="img/suffer.png" alt="Suffer" />
   		<h2 class="subhead">Don't suffer in silence</h2>
   		<p><a href="/post">Tell the story</a> of how you were wronged to the world.</p>
 	</div>
	<div class="heard feature">
		<img src="img/heard.png" alt="Suffer">
		<h2 class="subhead">Be heard with others</h2>
		<p>Obtain critical mass by submitting your complaint.</p>
	</div>
	<div class="right feature">
	  	<img src="img/right.png" alt="Suffer">
	   	<h2 class="subhead">Set things right</h2>
	   	<p>Hold companies responsible so it doesn't happen again.</p>
	 </div>
</div>
<div id="complaints_list" class="grid_8">
 	<div class="comps">
	 	<h2 class="indexComplaints">Complaints</h2>
 		<?php foreach($this->posts as $post) {?>
        	<div class='recentComplaints'>
             	<div class='userIcon'>
                	<img src="<?php echo $post['profile_photo'];?>"/>
             	</div>
           		<div class='blurb'><p class="first"><?php echo $post['firstname'];?></p><h4><a href='<?php echo "http://yousuckapp.com:8083/analytics/show?company=".$post['company_name']."&scale=day";?>'><?php echo $post['company_name'];?> You Suck</a></h4><p><?php echo $post['text'];?></p><p class='read-more'><a href="/post/item?id=<?php echo $post['id'];?>" class='button'>Read More</a></p></div>
         		<div class='totalComments'><span>7</span>comments</div>
   			</div>
 		<?php }?>
   		<div class="moreposts"><button class="button">View More Posts</button></div>
 	</div>    
</div>
<div class="grid_4">
 	<div class="posts">
	 	<a href="post" class="button postComplaint">Post Complaint</a>
	 	<p class="appStore"><img src="img/appstore.png"/></p>
 	</div>
</div>

   			 	