<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script src="/js/controllers/analytics_show.js"></script>

<h1 class="analytics">Analytics for [company]</h1>
<div id="chart" class="grid_8"></div>  
<div class="grid_4 trending">
	<h5>TRENDING NOW</h5>
	<div>
		<img src="/img/companies/delta.png"/>
		<em class="datebig">10/2</em>
		<ul>
			<li>Complaints</li>
			<li><a href="">View Thread</a></li>
		</ul>
	</div>
	<div>
		<img src="/img/companies/western_union.png" />
		<em class="datebig">10/2</em>
		<ul>
			<li>Complaints</li>
			<li><a href="">View Thread</a></li>
		</ul>
	</div>
	<div>
		<img src="/img/companies/safeway.png"/>
		<em class="datebig">10/2</em>
		<ul>
			<li>Complaints</li>
			<li><a href="">View Thread</a></li>
		</ul>
	</div>
	<img src="/img/available_at_iphone.png" />
</div>
