<div class="grid_12" clearfix loginModule>
	<div id="fb-root"></div>   
	<h1>Welcome back to the place where you're heard!</h1>
	<p id="loginRegister">If you don't have an account you can <a href="/user/register">register</a> easily.</p>
	<div id="loginArea" class="clearfix"> 
  		<div class="fb-login-button" data-scope="email">Login with Facebook</div>
  		<div class="defaultOr">or</div>
  		<form id="formLogin" action="login/login" method="get" class="login clearfix">
      		<div class="errorBox"></div>
      		<label for="username" class="accessAid">Email</label>
      		<input type="text" name="username" id="username" placeholder="Email Address"/>
      		<label for="password" class="accessAid"></label>
      		<input type="password" id="password" name="password" placeholder="Password"/>
      		<p class="forgot"><a href="">Forget your password?</a></p>
      		<input type="submit" value="login" class="button mob" />
  		</form>
	</div>
</div>
