<footer>
					<p>You Suck: Follow us on <a href="twitter.com">Twitter</a> or <a href="facebook.com">Facebook<a></p>
					<ul>
					  <li><a href="">About</a></li>
					  <li>|</li>
					  <li><a href="">Team</a></li>
					  <li>|</li>
					  <li><a href="">Blog</a></li>
					  <li>|</li>
					  <li><a href="">Help</a></li>	
					  <li>|</li>
					  <li><a href="">Terms</a></li>
					  <li>|</li>
					  <li><a href="">Log in</a></li>
					</ul>
</footer>