<footer>
	
	<ul>
		<li><a href="/index/about">About</a></li>
		<li>|</li>
	  	<li><a href="http://blankyousuck.tumblr.com/" target="_new">Blog</a></li>
	  	<li>|</li>
	  	<li><a href="https://twitter.com/#!/feedbakloop">Twitter</a></li>	
	  	<li>|</li>
	  	<li><a href="/index/terms">Terms</a></li>
	</ul>
        <script type="text/javascript">
            
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-28212941-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
                    
</footer>