<header class="main">
	<h1><a href="/" class="goHome">You <br/>Suck</a></h1>
	<div class="tasks">
		<div class="searchStuff">
			<form id="search_box" class="search">
		   		<input type="search" placeholder="Search companies"/>
	      		<a class="icon magnify">z</a>
	      	</form>
		   	<a href="/post" class="button vent">post complaint</a>
	   	</div>
	   	<ul>
	   		<li><a href="">About</a></li>
	   		<?php if ( !isset($this->user) || empty($this->user)){ ?>
	   			<li class="last"><a href="/login/default">Log in</a></li>
         	<?php } else { ?>
          		<li><a href="/post/mypost">My Post</a></li>
    			<li class="last"><a href="/login/logout">Log out</a></li>
      		<?php } ?>
	 	</ul>
	</div>
</header>