<header class="main">
	   				<h1><a href="/" class="goHome">You <br/>Suck</a></h1>
	   				<div class="tasks">
	   			 			<form id="search_box" class="search">
	   			 				<input type="search" placeholder="Search companies"/>
                                                                <a class="icon magnify">z</a>
	   			 			</form>
	   			 			<a href="post" class="button vent">post complaint</a>
	   			 			<ul>
	   			 		<li><a href="">About</a></li>
	   			 		<li><a href="">Team</a></li>
	   			 		<li><a href="http://blankyousuck.tumblr.com/" target="_new">Blog</a></li>
	   			 		<li><a href="">Help</a></li>	
	   			 		<li><a href="">Terms</a></li>
	   			 		<?php if ( !isset($this->user) || empty($this->user)){ ?>
	   			 		<li><a href="/login/default">Log in</a></li>
            <?php } else { ?>
    <li><a href="/login/logout">Log out</a></li>
            <?php } ?>
	   			 	</ul>
	   			 </div>
</header>