<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Welcome to You Suck App</title>
		<meta charset="utf-8" />
		<meta name="keywords" content="You suck, complaints, gripes, customer service, bad experience" />
		<meta name="description" content="We group your complaints so you can be heard" />
		<meta content='width=device-width, initial-scale=1.0' name='viewport'>
		<link rel="stylesheet" href="/css/ys.css" />
		<script src="/js/lib/jquery.js"></script>
		<script src="/js/lib/mustache.js"></script>
      	<script src="/js/index.js"></script>
	</head>
<body>
<div class="container_12 youSuck">
<?php 
	echo $this->render('header.phtml');
?>  
<?php
	//Main content 
	echo $this->layout()->content;
?>  
<?php 
	echo $this->render('footer.phtml');
?>  
</div>
</body>
</html>
        