<div class="grid_12">
	<h2 class="loginWelcome">We're here to help you get heard, welcome!</h2>
	<div id="loginRegister">
	  <p>If you already have an account you can just <a href="/login/default">login</a>.</p>
	</div>
	<div id="loginArea">
	  	<div class="fb-login-button" data-scope="email">Login with Facebook</div>
	  	<span id="spanOR">or</span>      
	  	<form id="formLogin" action="/user/registersubmit" method="POST">
	      	<div class="errorBox"></div>
	      	<input type="text" name="first_name" class="loginInput" placeholder="Your Name" />
	      	<input type="text" name="email" class="loginInput" placeholder="Email Address" />
	      	<input type="password" name="password" class="loginInput" placeholder="Password" />
	      	<input type="submit" value="Register" class="button" />
	  	</form>
	</div>
</div>

