<div class="grid_8">
	<h1>Enter your complaint</h1>
	<p>When writing your complaint please consider constructive suggestions and ideas.</p>
    <form id="complaints_form" method="post" action="">
      <div class="company">
	      <label for="company" class="label">Company:</label> 
	      <input type="text" id="company" name="company" />
      </div>
      <div class="synopsis">
	        <label for="synopsis" class="label">The backstory (no limit, go nuts)</label>
	        <textarea  name="synopsis" id="synopsis"></textarea>
      </div>
      <div id="postUserInfo" >
        <?php if($this->user) {?>  
      	<img src="img/people/blank_face.jpg"/>
      	<ul>
      		<li><?php echo $this->user->getFirstName();?></li>
      		<li>
      		  <input type="checkbox" name="make_anonymos" />
      		  <span><b>Make me anonymous</b> (Don't show my name)</span>
      		</li>      		
      	</ul>
      	<input id="postSubmit" class="button" type="submit" name="submit" value="submit" />
        <?php }?>
      </div>
        <?php if(!($this->user)) {?>  
	<div class="grid_12 clearfix loginModule">
		<p class="or first"><a href="/login/default">Login</a><span>or</span></p>
	  	<div class="login">
	  		<label for="name" class="accessAid">Name</label>
            <input type="text" id="name" name="name" class="" placeholder="Name" value="" />
            <label for="email" class="accessAid">Email</label>
            <input type="text" id="email" name="email" class="" placeholder="Email" value="" />
            <input id="postSubmit" class="button" type="submit" name="submit" value="submit" />
	 	</div>
	</div>
<?php }?>
    </form>
    </div>
    <div class="grid_4 trending">
    	<h5>TRENDING NOW</h5>
    	<div>
    		<img src="img/companies/delta.png"/>
    		<em class="datebig">10/2</em>
    		<ul>
    			<li>Complaints</li>
    			<li><a href="">View Thread</a></li>
    		</ul>
    	</div>
    	<div>
    		<img src="img/companies/western_union.png" />
    		<em class="datebig">10/2</em>
    		<ul>
    			<li>Complaints</li>
    			<li><a href="">View Thread</a></li>
    		</ul>
    	</div>
    	<div>
    		<img src="img/companies/safeway.png"/>
    		<em class="datebig">10/2</em>
    		<ul>
    			<li>Complaints</li>
    			<li><a href="">View Thread</a></li>
    		</ul>
    	</div>
    	<img src="img/available_at_iphone.png" />
    </div>



  
