<h1 class="accessAid">Enter your complaint</h1>
    <form id="complaints_form" method="post" action="" class="grid_8">
      <p id="suggestion">When writing your complaint please consider constructive suggestions and ideas.</p>
      
      <h5>Company:</h5> 
      <input type="text" name="company" class="company" />
      
      <div>
        <h5>The backstory (no limit, go nuts)</h5>
        <textarea  name="synopsys"></textarea>
      </div>
      
      <div id="postUserInfo" >
      	<img src="img/people/bobby.png"/>
      	<ul>
      		<li>Bobby B.</li>
      		<li>
      		  <input type="checkbox" name="make_anonymos" />
      		  <span><b>Make me anonymous</b> (Don't show my name)</span>
      		</li>      		
      	</ul>
      	<input id="postSubmit" class="button" type="submit" name="submit" value="submit" />
      </div>
      
    </form>
    <div class="grid_4 trending">
    	<h5>TRENDING NOW</h5>
    	<div>
    		<img src="img/companies/delta.png"/>
    		<em class="datebig">10/2</em>
    		<ul>
    			<li>Complaints</li>
    			<li><a href="">View Thread</a></li>
    		</ul>
    	</div>
    	<div>
    		<img src="img/companies/western_union.png" />
    		<em class="datebig">10/2</em>
    		<ul>
    			<li>Complaints</li>
    			<li><a href="">View Thread</a></li>
    		</ul>
    	</div>
    	<div>
    		<img src="img/companies/safeway.png"/>
    		<em class="datebig">10/2</em>
    		<ul>
    			<li>Complaints</li>
    			<li><a href="">View Thread</a></li>
    		</ul>
    	</div>
    	<img src="img/available_at_iphone.png" />
    </div>

  
