<h1>[Title of post]</h1>
<div class="grid_9">
	<p class="first"><?php echo $this->post->getText();?></p>
</div>
<div class="grid_3 clearfix">
	<a href="" class="button flag">Flag for abuse</a>
</div> 
<div id="comments_list" class="grid_12 commentsList">
	<h2>Comments</h2>
            <?php foreach($this->comments as $comment) {?>
            <div class="userComment">
                    <div class="grid_3">
                            <img src="../img/people/blank_face.jpg" />
                            <?php echo $comment->firstname;?>
                    </div>
                    <div class="grid_9">
                            <p class="first"><?php echo $comment->content;?></p>
                    </div>
            </div>
            <?php }?>
</div>
<div class="grid_12 postComment">
            <?php if(!isset($this->user)) {?>
	<p><a class="button" href="/login/default"/>Log in to Comment</a></p>
            <?php } else {?>
 	<div class="grid_3">
		<img src="../img/people/blank_face.jpg" />
		<?php echo $this->user->getFirstName();?>
	</div>
	<div class="grid_9">
	<form id="commentsForm">
  		<textarea></textarea>
      	<p><input type="submit" class="button" value="Post a Comment" /></p>
	</form>        
	</div>
	<?php } ?> 
</div>
                
