
	   		<h1 class="accessAid">About company page</h1>	 
	   		<div class="grid_9">
	   			<p class="first">This is the user's complaint. The Lean Startup provides a scientific approach to creating and managing startups and get a desired product to customers' hands faster. The Lean Startup method teaches you how to drive a startup-how to steer, when to turn, and when to persevere-and grow a business with maximum </p>
  			</div>
			<div class="grid_3">
				<a href="" class="button">Flag for abuse</a>
   			</div>
   		</div>
   		<div class="container_12">
   			<h2>Comments</h2>
   		</div>
   		<div class="container_12 userComment">
   			<div class="grid_3">
   				<img src="../img/people/blank_face.jpg" />
   				Username
   			</div>
   			<div class="grid_9">
   				<p class="first">This is other user's comment on the the complaint</p>
   			</div>
   		</div>
   		<div class="container_12 userComment">
   			<div class="grid_3">
   				<img src="../img/people/blank_face.jpg" />
   				Username
   			</div>
   			<div class="grid_9">
   				<p class="first">This is other user's comment on the the complaint</p>	
   			</div>
   		</div>
   		<div class="container_12">
   			<p><input type="submit" class="button" value="Log in to Comment" /></p>
   		</div>