<div id="mypost" class="grid_12">
    <h1>My Posts</h1>
    <div class="userprofile">
        <img src="../img/people/blank_face.jpg" />
        <span><?php echo $this->user->getFirstName();?></span>
    </div>
    <div class="monthPost">
    	<p class="month"><a href="post_list" class="monthLink">November (2)</a></p>
	    <div id="post_list" class="postList">
	        <?php foreach($this->posts as $post) {?>
	        <div class="post_item">
	        	<div class="nameDate">
		            <a class="companyName" href="http://yousuckapp.com:8083/analytics/show?company=<?php echo $post->company_name;?>&scale=day"><?php echo $post->company_name;?> You Suck</a>
		            <time datetime="2011-11-11" class="date">Nov 11, 2011</time>
	            </div>
	            <p><?php echo $post->text;?></p>
	            <p class="read-more"><a href="/post/item?id=<?php echo $post->id;?>" class="button">Read More</a></p>
	        </div>
	        <?php }?>
	    </div>
    </div>      
</div>
<script>
	$(function(){
		$(".monthLink").bind("click", toggleSlide);
		function toggleSlide(ev) {
			ev.preventDefault();
			$(this).parents(".month").next().slideToggle();
		}
	});
</script>    